-- MySQL Script generated by MySQL Workbench
-- Sun Oct 31 19:17:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- DROP DATABASE IF EXISTS BAMMScholarshipDB;
-- CREATE DATABASE IF NOT EXISTS BAMMScholarshipDB;
-- USE BAMMScholarshipDB;

-- -----------------------------------------------------
-- Table `Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Activity` ;

CREATE TABLE IF NOT EXISTS `Activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `activity_name` VARCHAR(45) NULL,
  `activity_type` VARCHAR(45) NULL,
  `activity_date` DATE NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivingSituation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivingSituation` ;

CREATE TABLE IF NOT EXISTS `LivingSituation` (
  `living_situation_id` INT NOT NULL AUTO_INCREMENT,
  `is_on_campus` TINYINT NULL,
  PRIMARY KEY (`living_situation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhDProgram`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PhDProgram` ;

CREATE TABLE IF NOT EXISTS `PhDProgram` (
  `phd_program_id` INT NOT NULL AUTO_INCREMENT,
  `student_phd_name` VARCHAR(45) NULL,
  `is_phd_track` TINYINT(1) NULL,
  `phd_program_area` VARCHAR(45) NULL,
  `phd_school_1stchoice` VARCHAR(45) NULL,
  `phd_school_2ndchoice` VARCHAR(45) NULL,
  `phd_school_3rdchoice` VARCHAR(45) NULL,
  `accepted_to_1st` TINYINT(1) NULL,
  `accepted_to_2nd` TINYINT(1) NULL,
  `accepted_to_3rd` TINYINT(1) NULL,
  `phd_attended` VARCHAR(45) NULL,
  `reason` VARCHAR(600) NULL,
  PRIMARY KEY (`phd_program_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `College` ;

CREATE TABLE IF NOT EXISTS `College` (
  `college_id` INT NOT NULL AUTO_INCREMENT,
  `college_name` VARCHAR(45) NULL,
  `college_address` VARCHAR(45) NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `student_phone` CHAR(10) NULL,
  `student_address` VARCHAR(45) NULL,
  `is_mentor` TINYINT NULL,
  `is_affiliate` TINYINT NULL,
  `livingsit_id` INT NULL,
  `phd_id` INT NULL,
  `college_id` INT NULL,
  `received_scholarship` TINYINT NULL,
  `has_extracurricular` TINYINT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `phd_student_fk_idx` (`phd_id` ASC) VISIBLE,
  INDEX `livingsit_student_fk_idx` (`livingsit_id` ASC) VISIBLE,
  INDEX `college_student_fk_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `livingsit_student_fk`
    FOREIGN KEY (`livingsit_id`)
    REFERENCES `LivingSituation` (`living_situation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `phd_student_fk`
    FOREIGN KEY (`phd_id`)
    REFERENCES `PhDProgram` (`phd_program_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `college_student_fk`
    FOREIGN KEY (`college_id`)
    REFERENCES `College` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Affiliate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affiliate` ;

CREATE TABLE IF NOT EXISTS `Affiliate` (
  `affiliate_id` INT NOT NULL AUTO_INCREMENT,
  `affiliate_name` VARCHAR(45) NULL,
  `affiliate_email` VARCHAR(45) NULL,
  `affiliate_phone` CHAR(10) NULL,
  `student_id` INT NULL,
  `affiliate_college` VARCHAR(45) NULL,
  PRIMARY KEY (`affiliate_id`),
  INDEX `student_fk_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `studentAffiliate_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Conference` ;

CREATE TABLE IF NOT EXISTS `Conference` (
  `conference_id` INT NOT NULL AUTO_INCREMENT,
  `conference_fund_amnt_allocated` INT NULL,
  `num_of_students_attended` INT NULL,
  `conference_name` VARCHAR(45) NULL,
  `conference_date` DATE NULL,
  `activity_id` INT NOT NULL,
  PRIMARY KEY (`conference_id`),
  INDEX `activity_fk_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `activity_fk`
    FOREIGN KEY (`activity_id`)
    REFERENCES `Activity` (`activity_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_description` VARCHAR(320) NULL,
  `course_name` VARCHAR(45) NULL,
  `is_math` TINYINT NOT NULL,
  `is_mandatory` TINYINT NOT NULL,
  `course_professor` VARCHAR(45) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Occupation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Occupation` ;

CREATE TABLE IF NOT EXISTS `Occupation` (
  `occupation_id` INT NOT NULL AUTO_INCREMENT,
  `occupation_type` VARCHAR(45) NULL,
  `is_full_time` TINYINT NULL,
  `extracurricular_id` INT NULL,
  `student_occ_name` VARCHAR(45) NULL,
  PRIMARY KEY (`occupation_id`),
  INDEX `extracurricular_fk_idx` (`extracurricular_id` ASC) VISIBLE,
  CONSTRAINT `extracurricular_fk`
    FOREIGN KEY (`extracurricular_id`)
    REFERENCES `Extracurricular` (`extracurricular_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Extracurricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Extracurricular` ;

CREATE TABLE IF NOT EXISTS `Extracurricular` (
  `extracurricular_id` INT NOT NULL AUTO_INCREMENT,
  `extracurricular_type` VARCHAR(45) NULL,
  `occupation_id` INT NULL,
  PRIMARY KEY (`extracurricular_id`))
  
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GuestSpeaker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GuestSpeaker` ;

CREATE TABLE IF NOT EXISTS `GuestSpeaker` (
  `guest_speaker_id` INT NOT NULL AUTO_INCREMENT,
  `guest_speak_name` VARCHAR(45) NULL,
  `guest_speak_email` VARCHAR(45) NULL,
  `is_faculty` TINYINT NULL,
  `is_in_person` TINYINT NULL,
  `is_alumni` TINYINT NULL,
  `faculty_id` INT NULL,
  `activity_id` INT NULL,
  PRIMARY KEY (`guest_speaker_id`),
  INDEX `activity_fk_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `activityguest_fk`
    FOREIGN KEY (`activity_id`)
    REFERENCES `Activity` (`activity_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faculty` ;

CREATE TABLE IF NOT EXISTS `Faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `faculty_name` VARCHAR(45) NULL,
  `is_bamm` TINYINT NULL,
  `faculty_email` VARCHAR(45) NULL,
  `faculty_phone` CHAR(10) NULL,
  `guest_speaker_id` INT NULL,
  `faculty_college` VARCHAR(45) NULL,
  `faculty_subject` VARCHAR(45) NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `guestspeaker_fk_idx` (`guest_speaker_id` ASC) VISIBLE,
  CONSTRAINT `guestspeaker_fk`
    FOREIGN KEY (`guest_speaker_id`)
    REFERENCES `GuestSpeaker` (`guest_speaker_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Major` ;

CREATE TABLE IF NOT EXISTS `Major` (
  `major_id` INT NOT NULL AUTO_INCREMENT,
  `major_name` VARCHAR(45) NULL,
  `major_description` VARCHAR(320) NULL,
  `major_department` VARCHAR(45) NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MentorAlumni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MentorAlumni` ;

CREATE TABLE IF NOT EXISTS `MentorAlumni` (
  `mentor_alumni_id` INT NOT NULL AUTO_INCREMENT,
  `mentor_name` VARCHAR(45) NULL,
  `mentor_email` VARCHAR(45) NULL,
  `mentor_phone` VARCHAR(45) NULL,
  `student_id` INT NULL,
  `mentor_college` VARCHAR(45) NULL,
  PRIMARY KEY (`mentor_alumni_id`),
  INDEX `student_fk_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `student_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResearchTopic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResearchTopic` ;

CREATE TABLE IF NOT EXISTS `ResearchTopic` (
  `research_topic_id` INT NOT NULL AUTO_INCREMENT,
  `research_topic_area` VARCHAR(45) NULL,
  `research_topic_advisor` VARCHAR(45) NULL,
  `research_topic_studentname` VARCHAR(45) NULL,
  PRIMARY KEY (`research_topic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScholarshipAmount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ScholarshipAmount` ;

CREATE TABLE IF NOT EXISTS `ScholarshipAmount` (
  `scholarship_amount_id` INT NOT NULL AUTO_INCREMENT,
  `scholarship_amnt_student` VARCHAR(45) NULL,
  `scholarship_date` YEAR(4) NULL,
  `is_first_year` TINYINT NULL,
  `is_completed` TINYINT NULL,
  PRIMARY KEY (`scholarship_amount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentLoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentLoan` ;

CREATE TABLE IF NOT EXISTS `StudentLoan` (
  `student_loan_id` INT NOT NULL AUTO_INCREMENT,
  `student_loan_type` VARCHAR(45) NULL,
  `student_loan_amount` INT NULL,
  `student_id` INT NULL,
  PRIMARY KEY (`student_loan_id`),
  INDEX `student_loan_student_FK_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `student_loan_student_FK`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentGroup` ;

CREATE TABLE IF NOT EXISTS `StudentGroup` (
  `student_group_id` INT NOT NULL AUTO_INCREMENT,
  `student_group_campus` VARCHAR(45) NULL,
  `num_of_students` VARCHAR(45) NULL,
  `student_group_date` YEAR(4) NULL,
  `student_group_faculty` VARCHAR(45) NULL,
  PRIMARY KEY (`student_group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subject` ;

CREATE TABLE IF NOT EXISTS `Subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `faculty_id` INT NULL,
  `professor` VARCHAR(45) NULL,
  `subject_type` VARCHAR(45) NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `subject_faculty_fk_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `subjectfaculty_fk`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `Faculty` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingAssistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingAssistant` ;

CREATE TABLE IF NOT EXISTS `TeachingAssistant` (
  `teaching_assistant_id` INT NOT NULL AUTO_INCREMENT,
  `ta_name` VARCHAR(45) NULL,
  `is_first_year_teaching` TINYINT NULL,
  `subject_teach_type` VARCHAR(45) NULL,
  `ta_email` VARCHAR(45) NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`teaching_assistant_id`),
  INDEX `student_fk_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `studentTA_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentConference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentConference` ;

CREATE TABLE IF NOT EXISTS `StudentConference` (
  `student_id` INT NOT NULL,
  `conference_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `conference_id`),
  INDEX `conf_student_fk_idx` (`conference_id` ASC) VISIBLE,
  CONSTRAINT `student_conf_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conf_student_fk`
    FOREIGN KEY (`conference_id`)
    REFERENCES `Conference` (`conference_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FacultySubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FacultySubject` ;

CREATE TABLE IF NOT EXISTS `FacultySubject` (
  `faculty_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `subject_faculty_fk_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `faculty_subject_fk`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `Faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subject_faculty_fk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FacultyConference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FacultyConference` ;

CREATE TABLE IF NOT EXISTS `FacultyConference` (
  `faculty_id` INT NOT NULL,
  `conference_id` INT NOT NULL,
  INDEX `conf_faculty_id_idx` (`conference_id` ASC) VISIBLE,
  CONSTRAINT `faculty_conf_id`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `Faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conf_faculty_id`
    FOREIGN KEY (`conference_id`)
    REFERENCES `Conference` (`conference_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentOccupation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentOccupation` ;

CREATE TABLE IF NOT EXISTS `StudentOccupation` (
  `student_id` INT NOT NULL,
  `occupatione_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `occupatione_id`),
  INDEX `occ_student_fk_idx` (`occupatione_id` ASC) VISIBLE,
  CONSTRAINT `student_occ_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `occ_student_fk`
    FOREIGN KEY (`occupatione_id`)
    REFERENCES `Occupation` (`occupation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentExtracurricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentExtracurricular` ;

CREATE TABLE IF NOT EXISTS `StudentExtracurricular` (
  `student_id` INT NOT NULL,
  `extra_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `extra_id`),
  INDEX `extra_student_fk_idx` (`extra_id` ASC) VISIBLE,
  CONSTRAINT `student_extra_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `extra_student_fk`
    FOREIGN KEY (`extra_id`)
    REFERENCES `Extracurricular` (`extracurricular_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeScholarshipAmount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeScholarshipAmount` ;

CREATE TABLE IF NOT EXISTS `CollegeScholarshipAmount` (
  `college_id` INT NOT NULL,
  `scholarship_id` INT NOT NULL,
  INDEX `college_schol_fk_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `college_schol_fk`
    FOREIGN KEY (`college_id`)
    REFERENCES `College` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `scho_college_fk`
    FOREIGN KEY (`scholarship_id`)
    REFERENCES `ScholarshipAmount` (`scholarship_amount_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeExtracurricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeExtracurricular` ;

CREATE TABLE IF NOT EXISTS `CollegeExtracurricular` (
  `college_id` INT NOT NULL AUTO_INCREMENT,
  `extracurricular_id` INT NOT NULL,
  INDEX `extra_college_fk_idx` (`extracurricular_id` ASC) VISIBLE,
  CONSTRAINT `college_exta_fk`
    FOREIGN KEY (`college_id`)
    REFERENCES `College` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `extra_college_fk`
    FOREIGN KEY (`extracurricular_id`)
    REFERENCES `Extracurricular` (`extracurricular_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentScholarshipAmount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentScholarshipAmount` ;

CREATE TABLE IF NOT EXISTS `StudentScholarshipAmount` (
  `student_id` INT NOT NULL,
  `scholarship_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `scholarship_id`),
  INDEX `scholar_student_fk_idx` (`scholarship_id` ASC) VISIBLE,
  CONSTRAINT `student_scholar_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `scholar_student_fk`
    FOREIGN KEY (`scholarship_id`)
    REFERENCES `ScholarshipAmount` (`scholarship_amount_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FacultyStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FacultyStudent` ;

CREATE TABLE IF NOT EXISTS `FacultyStudent` (
  `faculty_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `student_faculty_fk_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `faculty_student_fk`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `Faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_faculty_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentGroupStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentGroupStudent` ;

CREATE TABLE IF NOT EXISTS `StudentGroupStudent` (
  `studentg_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`studentg_id`, `student_id`),
  INDEX `student_studentg_fk_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `studentg_student_fk`
    FOREIGN KEY (`studentg_id`)
    REFERENCES `StudentGroup` (`student_group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_studentg_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentMajor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentMajor` ;

CREATE TABLE IF NOT EXISTS `StudentMajor` (
  `student_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `major_id`),
  INDEX `major_student_fk_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `student_major_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `major_student_fk`
    FOREIGN KEY (`major_id`)
    REFERENCES `Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentCourse` ;

CREATE TABLE IF NOT EXISTS `StudentCourse` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `course_student_fk_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `student_course_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_student_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseMajor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseMajor` ;

CREATE TABLE IF NOT EXISTS `CourseMajor` (
  `course_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  INDEX `major_course_fk_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `course_major_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `major_course_fk`
    FOREIGN KEY (`major_id`)
    REFERENCES `Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FacultyCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FacultyCourse` ;

CREATE TABLE IF NOT EXISTS `FacultyCourse` (
  `faculty_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`faculty_id`, `course_id`),
  INDEX `course_faculty_fk_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `faculty_course_fk`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `Faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_faculty_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TACourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TACourse` ;

CREATE TABLE IF NOT EXISTS `TACourse` (
  `ta_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`ta_id`, `course_id`),
  INDEX `course_ta_fk_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `ta_course_fk`
    FOREIGN KEY (`ta_id`)
    REFERENCES `TeachingAssistant` (`teaching_assistant_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_ta_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentResearch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `StudentResearch` ;

CREATE TABLE IF NOT EXISTS `StudentResearch` (
  `student_id` INT NOT NULL,
  `research_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `research_id`),
  INDEX `research_student_fk_idx` (`research_id` ASC) VISIBLE,
  CONSTRAINT `student_research_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `research_student_fk`
    FOREIGN KEY (`research_id`)
    REFERENCES `ResearchTopic` (`research_topic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
